#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Frog\Console\Application;

// Handle global color flags before running application
$filtered = [];
$forceColor = false;
$forceNoColor = false;
foreach ($argv as $i => $a) {
    if ($i === 0) {
        $filtered[] = $a;
        continue;
    }
    if ($a === '--no-color') {
        $forceNoColor = true;
        continue;
    }
    if ($a === '--color') {
        $forceColor = true;
        continue;
    }
    $filtered[] = $a;
}
if ($forceColor) {
    \Frog\Console\Command::enableColors(true);
} elseif ($forceNoColor) {
    \Frog\Console\Command::enableColors(false);
}

$app = new Application();
exit($app->run($filtered));
